port:  5000
markdown: kramdown
name: 开放数据沙龙
url: http://opendatasalon.github.io
title: 开放数据沙龙
description: "探讨中国数据开放进程"
encoding: utf-8
timezone: China/Beiijng
city: 上海
navigation:
- text: 主页
  url: /index.html
- text: 历次活动
  url: /events/index.html
  category: events
- text: 贡献你的力量
  url: https://github.com/opendatasalon/opendatasalon.github.io/issues
next: 下期活动预告 开放数据桌游
nexturl: 


